
project_id = "wztmgdevfzykdnqakwhg"

[functions.generate-steep-analysis]
verify_jwt = false

[functions.generate-scenario-matrix]
verify_jwt = false

[functions.generate-three-horizons]
verify_jwt = false

[functions.generate-dots-strategy]
verify_jwt = false
