// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wztmgdevfzykdnqakwhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dG1nZGV2Znp5a2RucWFrd2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjgzMDAsImV4cCI6MjA2NTUwNDMwMH0.fU-c5DhM_y6xn7V-SH3xOMH-KEshr4pE3pDcTTGkyb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);